package com.sakai.inventory.domain.model;

import jakarta.validation.constraints.NotBlank;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.UpdateBehavior;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.*;

import java.time.Instant;

@DynamoDbBean
public class Catalog {
    private String partitionKey;
    private String sortKey;
    @NotBlank(message = "Entity type must not be blank")
    private String entityType;
    private Instant updatedAt;
    private Instant createdAt;
    private String description;
    @NotBlank(message = "Catalog name must not be blank")
    private String name;
    private String color;
    private Boolean rendered = true;

    public Catalog() {
        super();
    }

    public Catalog(String name) {
        this.name = name;
    }

    @DynamoDbPartitionKey
    public String getPartitionKey() {
        return partitionKey;
    }

    public void setPartitionKey(String partitionKey) {
        this.partitionKey = partitionKey;
    }

    @DynamoDbSortKey
    @DynamoDbSecondarySortKey(indexNames = {"GSI_entityType", "GSI_ItemsInCatalogs"})
    public String getSortKey() {
        return sortKey;
    }

    public void setSortKey(String sortKey) {
        this.sortKey = sortKey;
    }

    @DynamoDbSecondaryPartitionKey(indexNames = {"GSI_entityType"})
    public String getEntityType() {
        return entityType;
    }

    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }

    @DynamoDbAutoGeneratedTimestampAttribute
    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }

    @DynamoDbAutoGeneratedTimestampAttribute
    @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS)
    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public Boolean getRendered() {
        return rendered;
    }

    public void setRendered(Boolean rendered) {
        this.rendered = rendered;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;

        Catalog catalog = (Catalog) o;
        return partitionKey.equals(catalog.partitionKey) && sortKey.equals(catalog.sortKey);
    }

    @Override
    public int hashCode() {
        int result = partitionKey.hashCode();
        result = 31 * result + sortKey.hashCode();
        return result;
    }

    @Override
    public String toString() {
        return "Catalog: {" +
                "partitionKey='" + partitionKey + '\'' +
                ", sortKey='" + sortKey + '\'' +
                ", entityType='" + entityType + '\'' +
                ", updatedAt='" + updatedAt + '\'' +
                ", createdAt='" + createdAt + '\'' +
                ", description='" + description + '\'' +
                ", name='" + name + '\'' +
                ", color='" + color + '\'' +
                ", rendered=" + rendered +
                '}';
    }
}
