services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      # API Gateway
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      # Services, die gestartet werden sollen
      - SERVICES=apigateway,cloudformation,cloudwatch,dynamodb,dynamodbstreams,events,iam,kinesis,kms,lambda,logs,s3,secretsmanager,sns,sqs,ssm,sts,apigatewayv2

      # Persistenz aktivieren (optional)
      - PERSISTENCE=1
      # - DATA_DIR=/var/lib/localstack/data

      # Für Lambda Funktionen
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      # - LAMBDA_DOCKER_NETWORK=localstack_default

      # Edge Port (wichtig für alle Services)
      - EDGE_PORT=4566

      # Debug Modus (optional)
      - DEBUG=1

      # AWS Credentials für lokale Entwicklung
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-central-1
      - LOCALSTACK_AUTH_TOKEN=ls-PexeyIsu-lURA-9398-zaWi-WaxI27420bd9
    volumes:
      # Für persistente Daten
      - localstack_data:/var/lib/localstack

      # Docker Socket für Lambda-Funktionen
      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - localstack-network
volumes:
  localstack_data:
    driver: local
#networks:
#  localstack-network:
#    driver: bridge